# ===================================
#  List Column Definitions
# ===================================

columns:

    name:
        label: djetson.shop::lang.list.name
        type: text
        searchable: 1

    sku:
        label: djetson.shop::lang.list.sku
        type: number
        width: 1%
        searchable: 1

    price:
        label: djetson.shop::lang.list.price
        type: price
        width: 140px
        searchable: 1

    quantity:
        label: djetson.shop::lang.list.quantity
        type: number
        width: 1%