# ===================================
#  Import/Export Behavior Config
# ===================================
import:
    title: Import products
    modelClass: Djetson\Shop\Models\ProductImport
    list: $/djetson/shop/models/productimport/columns.yaml

export:
    title: Export products
    modelClass: Djetson\Shop\Models\ProductExport
    list: $/djetson/shop/models/productexport/columns.yaml