# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: djetson.shop::lang.products.label

# Model Form Field configuration
form: $/djetson/shop/models/product/fields.yaml

# Model Class name
modelClass: Djetson\Shop\Models\Product

# Default redirect location
defaultRedirect: djetson/shop/products

# Create page
create:
    title: djetson.shop::lang.products.create
    redirect: djetson/shop/products/update/:id
    redirectClose: djetson/shop/products

# Update page
update:
    title: djetson.shop::lang.products.update
    redirect: djetson/shop/products
    redirectClose: djetson/shop/products

# Preview page
preview:
    title: djetson.shop::lang.products.preview
