# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: djetson.shop::lang.shipping_methods.label

# Model Form Field configuration
form: $/djetson/shop/models/shippingmethod/fields.yaml

# Model Class name
modelClass: Djetson\Shop\Models\ShippingMethod

# Default redirect location
defaultRedirect: djetson/shop/shippingmethods

# Create page
create:
    title: djetson.shop::lang.shipping_methods.create
    redirect: djetson/shop/shippingmethods/update/:id
    redirectClose: djetson/shop/shippingmethods

# Update page
update:
    title: djetson.shop::lang.shipping_methods.update
    redirect: djetson/shop/shippingmethods
    redirectClose: djetson/shop/shippingmethods

# Preview page
preview:
    title: djetson.shop::lang.shipping_methods.preview
